apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: anomaly-detector-pdb
  labels:
    app: anomaly-detector
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: anomaly-detector
  unhealthyPodEvictionPolicy: IfHealthyBudget
